### ISSUE TITLE
io.js support

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-pre-gyp#135]
io.js 1.0.1 is now out (https://iojs.org/) and node-pre-gyp packaged apps like node-sqlite3 and node-mapnik almost works out of the box. To get things working we'll need:

 - [x] Wait until https://github.com/iojs/io.js/issues/402 is fixed (refs https://github.com/iojs/io.js/issues/456)
 - [x] Add a `v1.0.2` target (or whatever the release is that fixes https://github.com/iojs/io.js/issues/402) to the `abi_crosswalk.json`
 - [x] Temporarily ignore the harmless `child_process: customFds option is deprecated, use stdio instead` in tests (until node-gyp release lands for https://github.com/TooTallNate/node-gyp/pull/533 - refs #125)

**Comment by rvagg** [comment]
v1.0.2 is in and should have that aws fix

**Comment by springmeyer** [comment]
Thank you @rvagg! Publishing v0.6.2 shortly with the minimal fixes needed for all tests to pass with io.js v1.0.2. NOTE: the only failing tests with node-pre-gyp (other than the aws cert) were related to the obscure/advanced support node-prep-gyp has (like node-gyp) for passing the --target flag. I use this to build and package windows binaries on linux travis machines for mapbox-studio: https://github.com/mapbox/mapbox-studio/blob/f988c5947268efd9c07487fb553e930dbeac437b/scripts/build-atom.sh#L81-L85
